[sprint_2]
viIena/middle.messenger.praktikum.yandex pull request #2
Opened 2022-07-17 20:41 UTC by viIena

2022-07-18 18:24 UTC, agadoev requested changes
Привет
Я не увидел следующего функционала:
- Класса для работы с HTTP запросами
- Логику страниц и компонентов
- Валидации форм

2022-07-18 18:24 UTC, agadoev commented on tsconfig.json
> +    "sourceMap": true
в настройках typescript стоит указать обязательно 
noImplicitAny: true
any по возможности лучше вообще не использовать в коде. Если неизвестно, какой будет тип - есть отличная альтернатива - unknown

2022-10-09 23:40 UTC, agadoev requested changes
Привет, @viIena 
Спасибо за работу
Я отметил те места, которые стоит поправить. Давай сделаем это и двинемся дальше :)

2022-10-09 23:40 UTC, agadoev commented on src/template/request.ts
> +}
Подумай над тем, чтобы использовать union вместо enum'a. Union не транспилируется в объект, как enum, и на не нужно дублировать код (сейчас для каждого элемента перечисления дублируется строка). Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2022-10-09 23:40 UTC, agadoev commented on src/template/request.ts
> +}
1. Поехало форматирование
2. Выглядит довольно сложно, я бы сделал попроще

```
return "?" + Object
 .entries(data)
 .map(([key, value]) => `${key}=${value}`)
 .join("&")
```
добавляется еще один проход по объекту за O(n), но сильно на производительность это не повлияет

2022-10-09 23:40 UTC, agadoev commented on src/template/request.ts
> +    request = (url: string, options: OptionsType, timeout = 5000) => {
timeout уже есть в объекте options. Сейчас его можно передать и через параметры, и через options. Давай оставим что-то одно.

2022-10-09 23:40 UTC, agadoev commented on src/utils/mask.ts
> +}
Каждая такая функция должна делать только одну вещь - проверять правильность переданного ей значения. Результатом такой функции должно быть boolean значение, а не строка. Текст ошибки должен прописываться на уровне шаблона. Попробуй сделать такой рефакторинг.

2022-10-09 23:40 UTC, agadoev commented on src/template/renderDOM.ts
> +  const root = document.querySelector('#app');
предлагаю вынести css селектор в аргументы функции. Это позволит избежать хардкода внутри этой фукнции.

2022-10-09 23:40 UTC, agadoev commented on src/pages/authorization/authorization.ts
> +                return true
```suggestion
                return error !== ''
```

2022-10-09 23:40 UTC, agadoev commented on src/pages/authorization/authorization.ts
> +                    })
Если здесь копируется объект, то его можно скопировать более простым способом
```suggestion
                    const data = {...this.refs}
```

2022-10-09 23:40 UTC, agadoev commented on src/pages/authorization/authorization.ts
> +                })
если мы берем тут только значения, то не имеет смысла использовать entries, лучше использовать values

2022-10-09 23:40 UTC, agadoev commented on src/utils/mask.ts
> +//TODO: перенести в const.js
Не очень удачное название файла mask.ts. Обычно маска - это для форматирования ввода, а тут валидация ввода. Это разные операции. Лучше назвать этот файл validators

2022-10-12 13:21 UTC, viIena commented on src/pages/authorization/authorization.ts
> +                    })
> Если здесь копируется объект, то его можно скопировать более простым способом

Не совсем. Если, я все правильно поняла, то:
Я хочу получить объект вида -> { 'login': 'Vilena' }, а вашим способом получиться -> { 'login': input }.

2022-10-12 16:13 UTC, viIena commented
> Привет Я не увидел следующего функционала:
> 
> * Класса для работы с HTTP запросами
> * Логику страниц и компонентов
> * Валидации форм
>   Если возникли трудности, ты можешь написать своему наставнику или мне, мои контакты у меня в профиле

Спасибо за ревью! Поправила)

2022-10-13 07:12 UTC, agadoev approved these changes
Привет, @viIena 
Спасибо за правки, вижу, что все ок. Т.к. задания выполнены - работа принимается :)
удачи в следующем спринте!

2022-10-13 09:57 UTC, merged